version: "3"
services:
  jwt-auth:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      SECRET: ${SECRET}
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - 27017:2017
